const Discord = require("discord.js")
const client = new Discord.Client(
    {intents:["GUILDS", "GUILD_MEMBERS", "GUILD_MESSAGES"] }
)

client.login(process.env.token)


    client.on("ready", () => {
        console.log("Bot ONLINE")
    })

    client.on("messageCreate", (message) => {
        if(message.content == "!saky"){
            message.channel.send("Ciao sono SakyMC. Digita s!list per avere la lista dei comandi.")
        }
    })

    
    client.on("messageCreate", (message) => {
        if(message.content == "s!invito"){
            message.channel.send("https://discord.gg/xE3WHSYF")
        }
    })

    client.on("messageCreate", (message) => {
        if(message.content == "s!serverinfo"){
            var embed = new Discord.MessageEmbed()
            .setDescription("**■▬▬▬▬▬▬◢◤◆◥◣▬▬▬▬▬▬■\n                       ・Saky MC・\n■▬▬▬▬▬▬◥◣◆◢◤▬▬▬▬▬▬■\n             \n╠《🔒》Stanze Private\n╠《🎶》Musica con Molti Bot, Anime\n╠《👮‍♂️》Self-Role\n╠《🎫》Ticket per Assistenza\n╠《◽》Sistema di Ranking\n╠《👨🏿‍🤝‍👨🏾》Partnership e Collaborazioni\n╠《🤝》Staff Accogliente, Disponibile e Attivo\n\n■▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬■\nBuona Permanenza E...\n               Divertiti! \n■▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬■**")
            .setColor("DARK_PURPLE")
            .setThumbnail("https://media.discordapp.net/attachments/935963945502646363/937700386599469096/20220131_142526_0000.png")
            message.channel.send({embeds: [embed]})
        }
        if(message.content == "s!requisiti"){
            var embed = new Discord.MessageEmbed()
            .setDescription("**100 a 300 Ping: No\n300 a 500 Ping: Here1\n500 a 1000 Ping: Everyone Here**")
            .setColor("DARK_PURPLE")
            .setThumbnail("https://media.discordapp.net/attachments/935963945502646363/937700386599469096/20220131_142526_0000.png")
            message.channel.send({embeds: [embed]})
        }
        if(message.content == "s!list") {
            var embed = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("__SakyMC Bot__")
            .setDescription("**s!list**=\nti da tutti i comandi\n**s!invito**=\nti fornisce il link del server\n**s!serverinfo**=\nti da le informazioni del server\n**s!userinfo [utente]=**\nti da le info su un utente, dopo il comando devi pingare su chi vuoi le info\n**s!rules**=\nti fornisce le regole \n**s!requisiti**=\nti fornisce i requisiti partnership\n**s!level [utente]**=\nti mostra i livelli di un utente\n**s!lb (leaderboard)**=\nti mostra la classifica di livellamento del server\n**s!xp add/remove [utente] [amount] (IN ARRIVO)**=\nti mostra i livelli di un utente\n**s!time**=\nti fornisce l'ora\n**s!say**=\nserve per far dire qualcosa al bot\n**s!gaytest [utente]**=\nti dice quanto sei gay (ovviamente non è vero, ti da un numero casuale ogni volta)\n**s!ping**=\nti mostra la latenza del Bot (ovvero il ping)")
            .setThumbnail("https://media.discordapp.net/attachments/935963945502646363/937700386599469096/20220131_142526_0000.png")
            .setTimestamp();
            message.channel.send({embeds: [embed]})
        }
    })

    client.on("message", (message) => {
        if(message.content == "s!rules") {
            var embed = new Discord.MessageEmbed()
            .setTitle("__Rules!!__")
            .setColor("DARK_PURPLE")
            .setDescription("**Nel momento in cui entrerai e registrerai un account sul server, tutte le regole qui riportate verranno accettate automaticamente dall'utente.\nNon mancare di rispetto allo staff\nNon insultare altri utenti, se hai riscontri segnalali allo staff\nPer non incombere un sanzioni leggi il regolamento completo del server\nRispetta tutti, niente omofobia,bestemmie e razzismo\nSe ricevi una sanzione per te ingiusta, appellarsi aprendo un ticket non te la toglierà, in tal caso la sanzione è veramente ingiusta, segnalalo in dm ad uno Staffer ponendo delle valide prove della tua innocenza,\nL'utente può rifiutare il regolamento in tutta libertà, ma ciò comporterà a sanzioni molto pesanti.\nNota: Il Regolamento è in continuo aggiornamento, è compito dell'utente informarsi sul regolamento vigente, la mancata lettura non può essere usata come scusa per non incombere in sanzioni.**")
            .setThumbnail("https://media.discordapp.net/attachments/935963945502646363/937700386599469096/20220131_142526_0000.png")
            message.channel.send({embeds: [embed]})
        }
    })
    client.on('message', (message) => {
        if(message.content == "s!time"){
            var data = new Date();
            var ora = data.getHours();
            var minuto = data.getMinutes();

            if (message.content == "s!time") {
                var embed = new Discord.MessageEmbed()
                .setTitle("**Sono le ore:**")
                .setDescription(ora + "**:**" + minuto)
                .setColor("DARK_PURPLE")
                message.channel.send({embeds: [embed]})
            }
        }
    });

    client.on("messageCreate", message => {
        if (message.content == "s!gaytest") {
            var embed1 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed2 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed3 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("** Sei gay al:**")
            .setDescription("****")
            var embed4 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed5 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed6 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed7 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed8 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed9 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed10 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed11 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed12 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed13 = new Discord.MessageEmbed() 
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed14 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed15 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed16 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed16 = new Discord.MessageEmbed() 
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed17 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed18 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed19 = new Discord.MessageEmbed() 
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed20 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed21 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed22 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed23 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed24 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed25 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed26 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed27 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed28 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed29 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed30 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed31 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed32 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed33 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed34 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed35 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed36 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed37 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed38 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed39 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed40 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed41 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed42 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed43 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed44 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed45 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed46 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed47 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed48 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed49 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed50 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed51 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed52 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed53 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed54 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed55 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed56 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed57 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed58 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed59 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed60 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed61 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed62 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed63 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed64 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed65 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed66 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed67 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed68 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed69 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var embed70 = new Discord.MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("**Sei gay al:**")
            .setDescription("****")
            var messaggi = [embed1, embed2, embed3, embed4, embed5, embed6, embed7, embed8, embed9, embed10, embed11, embed12, embed13, embed14, embed15, embed16, embed17, embed18, embed19, embed20, embed21, embed22, embed23, embed24, embed25, embed26, embed27, embed28, embed29, embed30, embed31, embed32, embed33, embed34, embed35, embed36, embed37, embed38, embed39, embed40, embed41, embed42, embed43, embed44, embed45, embed46, embed47, embed48, embed49, embed50, embed51, embed52, embed53, embed54, embed55, embed56, embed57, embed58, embed59, embed60, embed61, embed62, embed63, embed64, embed65, embed66, embed67, embed68, embed69, embed70, embed71, embed72, embed73, embed74, embed75, embed76, embed77, embed78, embed79, embed80, ]
            message.channel.send({ embeds: [messaggi[Math.floor(Math.random() * messaggi.length)]] });
        }
    })

    client.on("messageCreate", message => {
        if (message.content.startsWith("s!avatar")) {
            if (message.content.trim() == "s!avatar") {
                var utente = message.member;
            }
            else {
                var utente = message.mentions.members.first();
            }
            if (!utente) {
                return message.channel.send("Utente non trovato")
            }
            var embed = new Discord.MessageEmbed()
                .setColor("DARK_PURPLE")
                .setTitle(utente.user.tag)
                .setDescription("L'avatar di questo utente")
                .setImage(utente.user.displayAvatarURL({
                    dynamic: true,
                    format: "png",
                    size: 512
                }))
            message.channel.send({ embeds: [embed] })
        }
    })
    client.on("messageCreate", message => {
        if (message.content == "s!ping") {
            var embed = new Discord.MessageEmbed()
                .setColor("DARK_PURPLE")
                .setTitle("Ping del bot")
                .setDescription("Ecco la latenza del bot")
                .addField("Ping", `${client.ws.ping}ms`)
    
            message.channel.send({embeds: [embed]})
        }
    }) 

